services:
    postgres:
        image: postgres:17
        container_name: tasksync-postgres
        restart: on-failure # Restart container automatically if it crashes
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: tasksync # Database name to auto-create
        volumes:
            - pgdata:/var/lib/postgresql/data # Persist Postgres data outside the container

    otel-collector:
        image: otel/opentelemetry-collector-contrib:0.97.0
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "4317:4317" # OTLP gRPC
            - "4318:4318" # OTLP HTTP
            - "8888:8888" # Collector metrics
    prometheus:
        image: prom/prometheus
        ports: ["9090:9090"]
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    tempo:
        image: grafana/tempo:2.4.1
        ports:
            - "3200:3200"
    loki:
        image: grafana/loki:2.9.0
        ports:
            - "3100:3100"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
    pgdata: # Named volume to store Postgres data (managed by Docker)
