services:
    postgres:
        image: postgres:17
        container_name: tasksync-postgres
        restart: always # Restart container automatically if it crashes or after reboot
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: tasksync
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        image: kingdomax/tasksync-backend:latest
        container_name: tasksync-backend
        restart: always
        ports:
            - "5070:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=tasksync;Username=postgres;Password=123456789
            - GamificationApi__BaseUrl=http://gamification-api:3000
        depends_on:
            - postgres

    gamification-api:
        image: kingdomax/tasksync-gamapi:latest
        container_name: tasksync-gamapi
        restart: always
        ports:
            - "3000:3000"
        env_file:
            - ./gamification-api/.env.production # this is not good practice to commit .env.production file as part of repository
        depends_on:
            - postgres

    frontend:
        image: kingdomax/tasksync-frontend:latest
        container_name: tasksync-frontend
        restart: always
        ports:
            - "3039:80"
        depends_on:
            - backend
            - gamification-api

volumes:
    pgdata:
