services:
    postgres:
        image: postgres:17
        container_name: tasksync-postgres
        restart: on-failure # Restart container automatically if it crashes
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456789
            POSTGRES_DB: tasksync # Database name to auto-create
        volumes:
            - pgdata:/var/lib/postgresql/data # Persist Postgres data outside the container

    backend:
        build:
            context: . #  build from project roo
            dockerfile: backend/Dockerfile # Use Dockerfile in the ./backend directory
        container_name: tasksync-backend
        restart: on-failure
        ports:
            - "5070:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            # Use double underscore (__) to map to nested JSON config keys, use internal docker port 5432 for Postgres
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=tasksync;Username=postgres;Password=123456789
            - GamificationApi__BaseUrl=http://gamification-api:3000
        depends_on:
            - postgres # Start Postgres first

    gamification-api:
        build:
            context: ./gamification-api
        container_name: tasksync-gamapi
        restart: on-failure
        ports:
            - "3000:3000"
        env_file:
            - ./gamification-api/.env.production
        depends_on:
            - postgres

    frontend:
        build:
            context: ./frontend
        container_name: tasksync-frontend
        restart: on-failure
        ports:
            - "3039:80"
        depends_on:
            - backend # Ensure backend is up before serving frontend
            - gamification-api

volumes:
    pgdata: # Named volume to store Postgres data (managed by Docker)
