receivers:
    otlp:
        protocols:
            grpc:
            http:

exporters:
    prometheus:
        endpoint: "0.0.0.0:8888"
    loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
    tempo:
        endpoint: "tempo:4317"
        tls:
            insecure: true

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [tempo]
        metrics:
            receivers: [otlp]
            exporters: [prometheus]
        logs:
            receivers: [otlp]
            exporters: [loki]
