receivers:
    otlp:
        protocols:
            grpc:
            http:

exporters:
    prometheus:
        endpoint: "0.0.0.0:8889" #pull model

    otlp/tempo:
        endpoint: tempo:4319 #push model
        tls:
            insecure: true

    loki:
        endpoint: "http://loki:3100/loki/api/v1/push" #push model

    logging:
        loglevel: info

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp/tempo]
        metrics:
            receivers: [otlp]
            exporters: [prometheus]
        logs:
            receivers: [otlp]
            exporters: [loki]
